name: publish-prerelease

on:
  release:
    types:
      - published

jobs:
  call-publish-pypi-prerelease:
    if: github.event.release.prerelease
    uses: ./.github/workflows/publish-pypi.yaml
    with:
      pypi_repository_url: https://test.pypi.org/legacy/
    secrets:
      pypi_api_token: ${{ secrets.TEST_PYPI_API_TOKEN }}
  call-publish-pypi-release:
    if: !github.event.release.prerelease
    uses: ./.github/workflows/publish-pypi.yaml
    with:
      pypi_repository_url: https://upload.pypi.org/legacy/
    secrets:
      pypi_api_token: ${{ secrets.PYPI_API_TOKEN }}
